# Generated by Django 4.1.2 on 2022-11-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
