# Generated by Django 4.1.2 on 2022-11-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0007_appointment_first_name_appointment_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="phone_number",
            field=models.CharField(default=123123123, max_length=14),
            preserve_default=False,
        ),
    ]
